# Generated by Django 5.2.12 on 2026-03-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mlb_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("team_name", models.CharField(blank=True, max_length=50)),
                ("location_name", models.CharField(blank=True, max_length=100)),
                ("abbreviation", models.CharField(db_index=True, max_length=10)),
                ("team_code", models.CharField(blank=True, max_length=10)),
                ("file_code", models.CharField(blank=True, max_length=10)),
                ("league_id", models.PositiveIntegerField(blank=True, null=True)),
                ("league_name", models.CharField(blank=True, max_length=50)),
                ("division_id", models.PositiveIntegerField(blank=True, null=True)),
                ("division_name", models.CharField(blank=True, max_length=50)),
                ("sport_id", models.PositiveIntegerField(default=1)),
                ("first_year_of_play", models.CharField(blank=True, max_length=4)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mlb_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="USA", max_length=100),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("roof_type", models.CharField(blank=True, max_length=50)),
                ("turf_type", models.CharField(blank=True, max_length=50)),
                ("left_line", models.PositiveIntegerField(blank=True, null=True)),
                ("left_center", models.PositiveIntegerField(blank=True, null=True)),
                ("center", models.PositiveIntegerField(blank=True, null=True)),
                ("right_center", models.PositiveIntegerField(blank=True, null=True)),
                ("right_line", models.PositiveIntegerField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mlb_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("full_name", models.CharField(db_index=True, max_length=150)),
                ("first_name", models.CharField(blank=True, max_length=75)),
                ("last_name", models.CharField(blank=True, max_length=75)),
                ("primary_number", models.CharField(blank=True, max_length=5)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("birth_city", models.CharField(blank=True, max_length=100)),
                ("birth_country", models.CharField(blank=True, max_length=100)),
                ("height", models.CharField(blank=True, max_length=10)),
                ("weight", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, max_length=50)),
                ("position_abbreviation", models.CharField(blank=True, max_length=5)),
                ("position_type", models.CharField(blank=True, max_length=20)),
                (
                    "bat_side",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Left"), ("R", "Right"), ("S", "Switch")],
                        max_length=1,
                    ),
                ),
                (
                    "pitch_hand",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Left"), ("R", "Right"), ("S", "Switch")],
                        max_length=1,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("mlb_debut_date", models.DateField(blank=True, null=True)),
                ("last_played_date", models.DateField(blank=True, null=True)),
                ("headshot_url", models.URLField(blank=True, max_length=500)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="mlb.team",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mlb_id", models.CharField(blank=True, db_index=True, max_length=50)),
                ("person_name", models.CharField(blank=True, max_length=150)),
                (
                    "person_mlb_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("resolution_date", models.DateField(blank=True, null=True)),
                ("type_code", models.CharField(blank=True, max_length=10)),
                ("type_desc", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "from_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_transactions",
                        to="mlb.team",
                    ),
                ),
                (
                    "to_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_transactions",
                        to="mlb.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="team",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="mlb.venue",
            ),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mlb_pk", models.PositiveIntegerField(db_index=True, unique=True)),
                ("game_date", models.DateTimeField(db_index=True)),
                (
                    "official_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("S", "Spring Training"),
                            ("E", "Exhibition"),
                            ("R", "Regular Season"),
                            ("F", "Wild Card"),
                            ("D", "Division Series"),
                            ("L", "League Championship"),
                            ("W", "World Series"),
                        ],
                        default="R",
                        max_length=2,
                    ),
                ),
                ("season", models.PositiveIntegerField(db_index=True)),
                ("series_description", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("final", "Final"),
                            ("postponed", "Postponed"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("detailed_state", models.CharField(blank=True, max_length=50)),
                ("home_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "current_inning",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("inning_state", models.CharField(blank=True, max_length=10)),
                ("double_header", models.CharField(blank=True, max_length=1)),
                ("game_number", models.PositiveSmallIntegerField(default=1)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="mlb.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="mlb.team",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="mlb.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-game_date"],
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("season", models.PositiveIntegerField(db_index=True)),
                (
                    "standings_type",
                    models.CharField(
                        db_index=True, default="regularSeason", max_length=30
                    ),
                ),
                ("league_id", models.PositiveIntegerField()),
                ("division_id", models.PositiveIntegerField()),
                (
                    "division_rank",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "league_rank",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "wild_card_rank",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("sport_rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("losses", models.PositiveSmallIntegerField(default=0)),
                ("pct", models.CharField(blank=True, max_length=6)),
                ("games_back", models.CharField(blank=True, max_length=10)),
                ("wild_card_games_back", models.CharField(blank=True, max_length=10)),
                ("streak_code", models.CharField(blank=True, max_length=10)),
                ("last_ten", models.CharField(blank=True, max_length=10)),
                ("clinched", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="mlb.team",
                    ),
                ),
            ],
            options={
                "ordering": ["division_rank"],
                "unique_together": {("team", "season", "standings_type")},
            },
        ),
    ]
